export default {
    "login": "sagara-bit",
    "id": 83308697,
    "node_id": "MDQ6VXNlcjgzMzA4Njk3",
    "avatar_url": "https://avatars.githubusercontent.com/u/83308697?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sagara-bit",
    "html_url": "https://github.com/sagara-bit",
    "followers_url": "https://api.github.com/users/sagara-bit/followers",
    "following_url": "https://api.github.com/users/sagara-bit/following{/other_user}",
    "gists_url": "https://api.github.com/users/sagara-bit/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sagara-bit/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sagara-bit/subscriptions",
    "organizations_url": "https://api.github.com/users/sagara-bit/orgs",
    "repos_url": "https://api.github.com/users/sagara-bit/repos",
    "events_url": "https://api.github.com/users/sagara-bit/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sagara-bit/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 16,
    "public_gists": 0,
    "followers": 1,
    "following": 1,
    "created_at": "2021-04-27T19:05:14Z",
    "updated_at": "2022-12-11T11:41:11Z"
  
};